import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import dynamic from "next/dynamic";
import { useEffect } from "react";
import RTC from "../libs/rtc";

const Room = dynamic(() => import("../components/Room"), {
  ssr: false,
});

export default function Home() {
  // useEffect(() => {
  //   import("peerjs").then(({ default: Peer }) => {
  //     let peer = RTC.initChannel();
  //     console.log(peer);
  //   });
  // }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello</h1>
      <Room />
    </div>
  );
}
